from enum import Enum, auto

# Definieren Sie ein Enum für die Rassen


class Rasse(Enum):
    Terraner = auto()
    Zerg = auto()
    Protoss = auto()

# Erstellen Sie ein Dictionary, das die Benutzereingaben den Enum-Werten zuordnet


rasse_mapping = {
    '1': Rasse.Terraner,
    '2': Rasse.Zerg,
    '3': Rasse.Protoss,
    'terraner': Rasse.Terraner,
    'teraner': Rasse.Terraner,
    'Teraner': Rasse.Terraner,
    'T': Rasse.Terraner,
    'te': Rasse.Terraner,
    'ter': Rasse.Terraner,
    'terr': Rasse.Terraner,
    'terra': Rasse.Terraner,
    'terran': Rasse.Terraner,
    'terrane': Rasse.Terraner,
    'tera': Rasse.Terraner,
    'teran': Rasse.Terraner,
    'terane': Rasse.Terraner,
    'Te': Rasse.Terraner,
    'Ter': Rasse.Terraner,
    'Terr': Rasse.Terraner,
    'Terra': Rasse.Terraner,
    'Terran': Rasse.Terraner,
    'Terrane': Rasse.Terraner,
    'Tera': Rasse.Terraner,
    'Teran': Rasse.Terraner,
    'Terane': Rasse.Terraner,
    'Teritorium': Rasse.Terraner,
    'Terrakota': Rasse.Terraner,
    'Terrasse': Rasse.Terraner,
    'Terrestre': Rasse.Terraner,
    'Terrakotta': Rasse.Terraner,
    'teritorium': Rasse.Terraner,
    'terrakota': Rasse.Terraner,
    'terrasse': Rasse.Terraner,
    'terrestre': Rasse.Terraner,
    'terrakotta': Rasse.Terraner,
    't': Rasse.Terraner,
    'Zwerg': Rasse.Zerg,
    'z': Rasse.Zerg,
    'Z': Rasse.Zerg,
    'ze': Rasse.Zerg,
    'zer': Rasse.Zerg,
    'Ze': Rasse.Zerg,
    'Zer': Rasse.Zerg,
    'Zerknittern': Rasse.Zerg,
    'Zerbrechen': Rasse.Zerg,
    'Zerlegen': Rasse.Zerg,
    'Zerfetzen': Rasse.Zerg,
    'Zerren': Rasse.Zerg,
    'zerknittern': Rasse.Zerg,
    'zerbrechen': Rasse.Zerg,
    'zerlegen': Rasse.Zerg,
    'zerfetzen': Rasse.Zerg,
    'zerren': Rasse.Zerg,
    'zerg': Rasse.Zerg,
    'zwerg': Rasse.Zerg,
    'Protos': Rasse.Protoss,
    'P': Rasse.Protoss,
    'pr': Rasse.Protoss,
    'pro': Rasse.Protoss,
    'prot': Rasse.Protoss,
    'proto': Rasse.Protoss,
    'Pr': Rasse.Protoss,
    'Pro': Rasse.Protoss,
    'Prot': Rasse.Protoss,
    'Proto': Rasse.Protoss,
    'Proton': Rasse.Protoss,
    'Protege': Rasse.Protoss,
    'Problem': Rasse.Protoss,
    'proton': Rasse.Protoss,
    'protege': Rasse.Protoss,
    'problem': Rasse.Protoss,
    'protoss': Rasse.Protoss,
    'protos': Rasse.Protoss,
    'p': Rasse.Protoss,
}
